services:
  # Backend API Service
  - type: web
    name: military-hierarchy-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt && python database/setup.py
    startCommand: cd backend && gunicorn backend:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 90 --graceful-timeout 90
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /hierarchy

  # Frontend Service
  - type: web
    name: military-hierarchy-frontend
    runtime: node
    plan: free
    rootDir: mil_dashboard
    buildCommand: npm install --force && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: military-hierarchy-backend
          envVarKey: RENDER_EXTERNAL_URL
